### ISSUE TITLE
Database is not initialized

### ISSUE THREAD

**Issue by joeframbach** [Xantier/nerd-stack#31]
I have cloned the repo, and in the rethinkdb administrative panel created a `nerd_stack_dev` database. It doesn't look like the db is initialized with any tables. In fact I don't think nerd-stack is connecting to rethinkdb at all :/

Any pointers here? Here's the output of `gulp` with some errors.

    $ gulp
    [22:33:23] Using gulpfile ~/git/nerd-stack/gulpfile.js
    [22:33:23] Starting 'scripts'...
    [22:33:24] Finished 'scripts' after 365 ms
    [22:33:24] Starting 'styles'...
    [22:33:24] Finished 'styles' after 147 ms
    [22:33:24] Starting 'build'...
    [22:33:24] Finished 'build' after 10 μs
    [22:33:24] Starting 'serve'...
    [22:33:24] Finished 'serve' after 90 ms
    [22:33:24] Starting 'default'...
    [22:33:24] Finished 'default' after 19 μs
    [22:33:24] [nodemon] v1.3.7
    [22:33:24] [nodemon] to restart at any time, enter `rs`
    [22:33:24] [nodemon] watching: app/**/*.js app/**/*.jsx spec/**/*.spec.js
    [22:33:24] [nodemon] starting `node run.js`
    info: Overriding Express logger
    Possibly unhandled Error: invalid argument: `family` must be 4 or 6
        at Object.exports.lookup (dns.js:113:13)
        at Socket.connect (net.js:908:20)
        at Object.exports.connect.exports.createConnection (net.js:86:35)
        at new Connection (/home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:41:25)
        at /home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/rethinkdbdash/lib/index.js:79:5
        at tryCatch2 (/home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/bluebird/js/main/util.js:51:21)
        at Promise$_resolveFromResolver [as _resolveFromResolver] (/home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/bluebird/js/main/promise.js:585:13)
        at new Promise (/home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/bluebird/js/main/promise.js:82:37)
        at r.connect (/home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/rethinkdbdash/lib/index.js:78:11)
        at Pool.createConnection (/home/joeframbach/git/nerd-stack/node_modules/thinky/node_modules/rethinkdbdash/lib/pool.js:177:18)

**Comment by joeframbach** [comment]
I updated to latest `node` version and it worked!

**Comment by Xantier** [comment]
Which version of node did and didn't work? I've been only on Linux Mint + io.js lately, so I think it would be beneficial to document environments.

**Comment by joeframbach** [comment]
Node 0.11 did not work. 0.12 did work. One of the dependencies has a
dependency of >=0.12.
