### ISSUE TITLE
nodemon error: extension.match is not a function

### ISSUE THREAD

**Issue by JoelSanchez** [Xantier/nerd-stack#36]
```
joel ~/Desarrollo/nerd-stack git:master o % gulp dev
[22:08:55] Using gulpfile ~/Desarrollo/nerd-stack/gulpfile.js
[22:08:55] Starting 'lint'...
[22:08:55] Starting 'scripts'...
[22:08:56] Finished 'scripts' after 350 ms
[22:08:56] Starting 'styles'...
[22:08:56] Finished 'styles' after 219 ms
[22:08:56] Starting 'build'...
[22:08:56] Finished 'build' after 7.93 μs
[22:08:56] Starting 'serve'...
[22:08:56] Finished 'serve' after 250 ms
/home/joel/Desarrollo/nerd-stack/node_modules/nodemon/lib/config/exec.js:158
  extension = extension.match(/\w+/g).join(',');
                        ^

TypeError: extension.match is not a function
    at exec (/home/joel/Desarrollo/nerd-stack/node_modules/nodemon/lib/config/exec.js:158:25)
    at /home/joel/Desarrollo/nerd-stack/node_modules/nodemon/lib/config/load.js:56:29
    at callback (/home/joel/Desarrollo/nerd-stack/node_modules/nodemon/lib/config/load.js:161:5)
    at ReadFileContext.callback (/home/joel/Desarrollo/nerd-stack/node_modules/nodemon/lib/config/load.js:171:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)

```

I solved it changing:

```
 ext: ['js', 'jsx'],
```

to:

```
 ext: 'js, jsx',
```

in gulpfile.js, line 60.

Don't know if the change is for good, but at least it does not crash.

**Comment by Xantier** [comment]
Thanks Joel,

Seems that gulp-nodemon plugin changed the way they are watching files. I updated the project with your proposed solution.
