### ISSUE TITLE
Cannot read property 'init' of undefined on $ gulp dev

### ISSUE THREAD

**Issue by DGaffneyDC** [Xantier/nerd-stack#38]
I've migrated my postgresql database successfully using gulp migrate, but running gulp dev returns this large error message:

`[18:30:05] Using gulpfile ~/Desktop/repos/nerd-stack/gulpfile.js
[18:30:05] Starting 'lint'...
[18:30:06] Starting 'scripts'...
[18:30:06] Finished 'scripts' after 125 ms
[18:30:06] Starting 'styles'...
[18:30:06] Finished 'styles' after 51 ms
[18:30:06] Starting 'build'...
[18:30:06] Finished 'build' after 1.47 μs
[18:30:06] Starting 'serve'...
[18:30:06] Finished 'serve' after 133 ms
[18:30:06] [nodemon] 1.10.2
[18:30:06] [nodemon] to restart at any time, enter `rs`
[18:30:06] [nodemon] watching: app/**/*.js app/**/*.jsx spec/**/*.spec.js
[18:30:06] [nodemon] starting `node run.js`
error: uncaughtException: Cannot read property 'init' of undefined date=Tue Aug 30 2016 18:30:07 GMT-0400 (EDT), pid=42812, uid=501, gid=20, cwd=/Users/Dylan/Desktop/repos/nerd-stack, execPath=/usr/local/bin/node, version=v6.5.0, argv=[/usr/local/bin/node, /Users/Dylan/Desktop/repos/nerd-stack/run.js], rss=62377984, heapTotal=43028480, heapUsed=27065904, loadavg=[2.85546875, 2.3388671875, 1.9619140625], uptime=967272, trace=[column=47, file=/Users/Dylan/Desktop/repos/nerd-stack/app/config/db.js, function=exports.default, line=4, method=default, native=false, column=12, file=/Users/Dylan/Desktop/repos/nerd-stack/app.js, function=, line=14, method=null, native=false, column=32, file=module.js, function=Module._compile, line=556, method=_compile, native=false, column=5, file=/Users/Dylan/Desktop/repos/nerd-stack/node_modules/babel/node_modules/babel-core/lib/api/register/node.js, function=normalLoader, line=199, method=null, native=false, column=7, file=/Users/Dylan/Desktop/repos/nerd-stack/node_modules/babel/node_modules/babel-core/lib/api/register/node.js, function=Object.require.extensions.(anonymous function) [as .js], line=216, method=require.extensions.(anonymous function) [as .js], native=false, column=32, file=module.js, function=Module.load, line=473, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=432, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=424, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=483, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false], stack=[TypeError: Cannot read property 'init' of undefined,     at exports.default (/Users/Dylan/Desktop/repos/nerd-stack/app/config/db.js:4:47),     at Object.<anonymous> (/Users/Dylan/Desktop/repos/nerd-stack/app.js:14:12),     at Module._compile (module.js:556:32),     at normalLoader (/Users/Dylan/Desktop/repos/nerd-stack/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5),     at Object.require.extensions.(anonymous function) [as .js] (/Users/Dylan/Desktop/repos/nerd-stack/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7),     at Module.load (module.js:473:32),     at tryModuleLoad (module.js:432:12),     at Function.Module._load (module.js:424:3),     at Module.require (module.js:483:17),     at require (internal/module.js:20:19)]
[18:30:07] Using gulpfile ~/Desktop/repos/nerd-stack/gulpfile.js
[18:30:07] Starting 'livereload'...
[18:30:07] Finished 'livereload' after 56 ms
`

There's a ton there, clearly, but it seems like the main culprit is the config variable in db.js. I'm not sure how to troubleshoot this exactly.

**Comment by DGaffneyDC** [comment]
100% user error. Didn't switch the first value of config.db to "bookshelf".
